import { createElement } from 'lwc';
import Merkel_custom_bar_format_spinner from 'c/merkel_custom_bar_format_spinner';

describe('c-merkel-custom-bar-format-spinner', () => {
    afterEach(() => {
        // The jsdom instance is shared across test cases in a single file so reset the DOM
        while (document.body.firstChild) {
            document.body.removeChild(document.body.firstChild);
        }
    });

    it('TODO: test case generated by CLI command, please fill in test logic', () => {
        // Arrange
        const element = createElement('c-merkel-custom-bar-format-spinner', {
            is: Merkel_custom_bar_format_spinner
        });

        // Act
        document.body.appendChild(element);

        // Assert
        // const div = element.shadowRoot.querySelector('div');
        expect(1).toBe(1);
    });
});